### ISSUE TITLE
Vocabulary for the model

### ISSUE THREAD

**Issue by p-null** [matthew-z/R-net#13]
Hi, Lucky to find your work here! 
So, i see you are using bert according to this file `hkust+bert.jsonnet`
However, 
1. Maybe I miss something but i didn't find `from_params()` method in R_Net.py. Is that `from_params()` the function we are supposed to implement?
2. Since every allennlp model needs a vocab for initialization, i was wondering what is the vocab for model initialization in 'hkust+bert.jsonnet` experiment?
3. Since you use a pre-trained bert model, how did you pass the pre-built [vocab](https://github.com/allenai/allennlp/blob/3fd224fc921e8e13ab89de1e6b8b3f16494d0435/allennlp/data/token_indexers/wordpiece_indexer.py#L209)(provided by Hugging face) to the allennlp model? 
Thank you!

**Comment by matthew-z** [comment]
1. `from_params` has been implemented since `RNet`model is a subclass of `allennlp.Model`.

2+3: the vocab is loaded from the Hugging face pre-built model. You may see that the `token_indexer` is `bert-pretrained`, which is implemented here: https://github.com/allenai/allennlp/blob/3fd224fc921e8e13ab89de1e6b8b3f16494d0435/allennlp/data/token_indexers/wordpiece_indexer.py#L196-L248

BTW, currently the bert version is not as good as the elmo one for some reasons. I have not got time to fix them.

**Comment by p-null** [comment]
I see your point but the vocab loaded from hf is not a `allennlp.Vocabulary`  and every `allennlp.Model` needs a vocab for initialization.
I see the line [here](https://github.com/allenai/allennlp/blob/1938a5af6d1ea3a2d8dccbb831f82990800fa3e1/allennlp/data/token_indexers/wordpiece_indexer.py#L240), the pretrained vocab is passed to initialize the `token_indexer`
What i was curious is, 
there is step(or i should say a piece of code) where it passes a vocabulary(the pretrained one) to initialize an `allennlp.Model`, right? but where is it?

I also see you didn't use the specific optimizer BertAdam for your model. You probably wanna give it a try :) But i am not sure that's kind of reason behind the performance.

**Comment by matthew-z** [comment]
The `vocab` in` Rnet. __init__` is not the `vocab` in the BERTtokenizer .

The former one is just an empty `allennlp.Vocabulary ` in `__init__`, and will add tokens from tokenized batches after initializing `Model`.  The latter one is used in tokenizing each batches before training.

We have to include the former `vocab` because it is required by allennlp, but it is useless for BERT and ELMo. Even for traditional glove and word2vec, It becomes an issue for AllenNLP: the vocab only includes tokens in training and validation dataset to reduce the usage of memory, but there are much more tokens in the pre-trained embeddings which should be utilized in testing to prevent OOV.

**Comment by p-null** [comment]
Aha, you cleared my mind!
Thanks!
