### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by opcoder** [matthew-z/R-net#8]
any performance of this code on SQuAD?

**Comment by matthew-z** [comment]
About 65 on F1, which is much lower than the paper's. I will recommend this implementation:  [https://github.com/HKUST-KnowComp/R-Net](https://github.com/HKUST-KnowComp/R-Net) if you are looking for high performance. If you want to exceed human performance, you need to use CoVe Word Embedding instead of Glove.

**Comment by opcoder** [comment]
Thanks a lot.
